version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Installing GoogleMaps API
      - pip install -U googlemaps
      - echo Compiling the Python code...
      - python locate.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - create-payment.py
